server:
  port: 8092
  servlet:
    context-path: /athena
spring:
  application:
    name: athena
  config:
    import: optional:file:/usr/local/etc/athena/application.properties
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
  sleuth:
    quartz:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
  mapper-locations: classpath:mapper/**/*.xml

