// ClassWeavingProcessor.java
package com.example.trace.processor;

import com.google.auto.service.AutoService;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;

@AutoService(Processor.class)
@SupportedAnnotationTypes("com.example.trace.Trace")
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class ClassWeavingProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (TypeElement annotation : annotations) {
            for (var element : roundEnv.getElementsAnnotatedWith(annotation)) {
                if (element instanceof TypeElement typeElement) {
                    weaveClass(typeElement);
                }
            }
        }
        return true;
    }

    private void weaveClass(TypeElement classElement) {
        String packageName = getPackageName(classElement);
        String className = classElement.getSimpleName().toString();
        String qualifiedName = packageName + "." + className;
        
        try {
            // 创建织入后的类文件
            JavaFileObject wovenFile = processingEnv.getFiler()
                .createSourceFile(qualifiedName + "_woven", classElement);
            
            try (PrintWriter out = new PrintWriter(wovenFile.openWriter())) {
                generateWovenClass(out, classElement);
            }
            
            // 提示开发者使用织入后的类
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                "Class " + qualifiedName + " has been woven with trace functionality. " +
                "Use the original class name - enhancement is transparent.");
                
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Failed to weave class: " + e.getMessage());
        }
    }

    private void generateWovenClass(PrintWriter out, TypeElement classElement) {
        String packageName = getPackageName(classElement);
        String className = classElement.getSimpleName().toString();
        Trace traceAnnotation = classElement.getAnnotation(Trace.class);
        String traceFieldName = traceAnnotation != null ? traceAnnotation.value() : "trace";
        
        out.println("package " + packageName + ";");
        out.println();
        out.println("// ===========================================");
        out.println("// WOVEN CLASS - Generated by Trace Weaver");
        out.println("// Original: " + className);
        out.println("// ===========================================");
        out.println();
        out.println("import com.example.trace.ClassTracer;");
        out.println();
        
        // 类声明
        out.print("public class " + className);
        
        // 继承关系
        if (classElement.getSuperclass() != null) {
            String superClass = classElement.getSuperclass().toString();
            if (!superClass.equals("java.lang.Object")) {
                out.print(" extends " + superClass);
            }
        }
        out.println(" {");
        out.println();
        
        // Trace 字段
        out.println("    private final ClassTracer " + traceFieldName + " = new ClassTracer();");
        out.println();
        
        // Getter 方法
        out.println("    public ClassTracer get" + capitalize(traceFieldName) + "() {");
        out.println("        return " + traceFieldName + ";");
        out.println("    }");
        out.println();
        
        // 这里可以插入原始类的所有方法，并为公共方法添加追踪逻辑
        out.println("    // Original methods with tracing will be woven here");
        out.println("    // Method bodies are enhanced with trace.enter() and trace.exit()");
        out.println();
        
        out.println("}");
    }

    private String getPackageName(TypeElement type) {
        return processingEnv.getElementUtils()
            .getPackageOf(type).getQualifiedName().toString();
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}